import {StyleSheet} from 'react-native';
import {theme} from './theme';


export default StyleSheet.create({
  rootContainer: {
    flex: 1,
  },
  headerIcon: {
    marginRight: 4,
  },
  headerText: {
    marginRight: 4,
    color: theme.colors.blackV0,
    fontSize: theme.fontSize.size22,
    fontWeight: '700',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerContainer: {
    backgroundColor: theme.colors.white,
  },
  container: {
    paddingTop: 50,
    flex: 1,
    backgroundColor: theme.colors.grayV3,
    justifyContent: 'space-between',
  },
  enterBox: {
    borderRadius: 999,
    backgroundColor: 'rgba(215, 215, 215, 0.50)',
    paddingVertical: 5,
    paddingHorizontal: 26,
    alignSelf: 'center',
    color: theme.colors.blackV3,
  },
  list: {
    flex: 1,
    paddingLeft: 15,
  },
  addBtn: {
    width: 30,
    height: 30,
    backgroundColor: theme.colors.Galdae3,
    marginRight: 10,
    borderRadius: 999,
  },
  sendBtn: {
    width: 34,
    height: 34,
    backgroundColor: theme.colors.blue,
    marginLeft: 12,
    borderRadius: 999,
  },
  inputBox: {
    flex: 1,
    height: 'auto',
    flexWrap: 'wrap',
    borderRadius: theme.borderRadius.size12,
    backgroundColor: theme.colors.grayV2,
    fontSize: theme.fontSize.size14,
    fontWeight: '500',
    color: theme.colors.blackV3,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  inputContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.colors.white,
    width: '100%',
    padding: 15,
    paddingBottom: 30,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  extraView: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    backgroundColor: theme.colors.white,
  },
  extraViewContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 15,
    marginRight: 12,
  },
  extraViewItem: {
    borderRadius: 999,
    width: 70,
    height: 70,
    backgroundColor: theme.colors.grayV3,
  },
  extraViewItemIcon: {
    width: 28,
    height: 28,
  },
  extraViewItemText: {
    marginTop: 6,
    fontSize: 14,
    color: theme.colors.blackV0,
    fontWeight: '500',
  },
  inputWrapper: {
    width: '100%',
  },
  sideMenu: {
    backgroundColor: theme.colors.white,
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    flex: 1,
    justifyContent: 'space-between',
    zIndex: 999,
  },
  menuUserList: {
    justifyContent: 'flex-start',
    flex: 1,
  },
  menuText: {
    color: theme.colors.blackV0,
    fontSize: theme.fontSize.size18,
    fontWeight: '700',
    marginTop: 55,
    marginBottom: 24,
    paddingLeft: 20,
    letterSpacing: -0.4,
  },
  menuUserIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
  },
  menuUserText: {
    fontSize: theme.fontSize.size16,
    fontWeight: '500',
    color: theme.colors.blackV0,
    marginRight: 8,
  },
  menuUserMe: {
    backgroundColor: theme.colors.blue2,
    width: 16,
    height: 16,
    borderRadius: 999,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuUserMeText: {
    color: theme.colors.blue,
    fontSize: theme.fontSize.size10,
    fontWeight: '700',
  },
  menuUserWrapper: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  menuUserContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  menuUserBtn: {
    backgroundColor: theme.colors.Galdae,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: theme.borderRadius.size12,
  },
  menuUserBtnText: {
    fontSize: theme.fontSize.size12,
    fontWeight: '500',
    color: theme.colors.white,
  },
  exitIconContainer: {
    position: 'absolute',
    right: 20,
    bottom: 30,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 998,
  },
});
