import { StyleSheet } from 'react-native';
import { theme } from './theme';

export default StyleSheet.create({
    container: {
        paddingTop: 50,
        flex: 1,
        backgroundColor: theme.colors.lightGray,
    },
    list: {
        flex: 1,
        paddingLeft: 15,
    },
    addBtn: {
        width: 30,
        height: 30,
        backgroundColor: theme.colors.brandSubColor,
        marginRight: 10,
        borderRadius: 999,
    },
    sendBtn: {
        width: 34,
        height: 34,
        backgroundColor: theme.colors.brandColor,
        marginLeft: 12,
        borderRadius: 999,
    },
    input: {
        flex: 1,
        height: 'auto',
        flexWrap: 'wrap',
        borderRadius: 10,
        backgroundColor: '#E9E9E9',
        fontSize: theme.fontSize.size14,
        fontWeight: '500',
        color: theme.colors.black,
        paddingHorizontal: 12,
    },
    inputContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: theme.colors.white,
        width: '100%',
        padding: 15,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
    },
    extraView: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        backgroundColor: theme.colors.white,
    },
    extraViewContainer: {
        paddingTop: 15,
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        paddingLeft: 15,
        marginRight: 12,
    },
    extraViewItem: {
        borderRadius: 999,
        width: 70,
        height: 70,
        backgroundColor: theme.colors.lightGray,
    },
    extraViewItemIcon: {
        width: 28,
        height: 28,
    },
    extraViewItemText: {
        marginTop: 6,
        fontSize: 14,
        color: theme.colors.gray2,
        fontWeight: '500',
    },
    inputWrapper: {
        width: '100%',
    },
    sideMenu: {
        backgroundColor: theme.colors.white,
        position: 'absolute',
        right: 0,
        top: 0,
        bottom: 0,
        flex: 1,
        justifyContent: 'space-between',
        zIndex: 999,
    },
    menuUserList: {
        justifyContent: 'flex-start',
        flex:1,
    },
    menuText: {
        color: theme.colors.black,
        fontSize: theme.fontSize.size20,
        fontWeight: '700',
        marginTop: 57,
        marginBottom: 36,
        paddingLeft: 20,
    },
    menuUserIcon: {
        marginRight: 15,
    },
    menuUserText: {
        fontSize: theme.fontSize.size18,
        fontWeight: '500',
        color: theme.colors.black,
        marginRight: 10,
    },
    menuUserMe: {
        backgroundColor: theme.colors.brandSubColor,
        width: 18,
        height: 18,
        color: theme.colors.brandColor,
        fontSize: theme.fontSize.size12,
        fontWeight: '700',
        borderRadius: 999,
        textAlign: 'center',
    },
    menuUserWrapper: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
        alignItems: 'center',
    },
    menuUserContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        marginBottom: 16,
    },
    menuUserBtn: {
        backgroundColor: theme.colors.brandColor,
        paddingHorizontal: 7,
        paddingVertical: 5,
        borderRadius: 10,
    },
    menuUserBtnText: {
        fontSize: theme.fontSize.size14,
        fontWeight: '500',
        color: theme.colors.white,
    },
    exitIcon: {
        position: 'absolute',
        right: 20,
        bottom: 30,
    },
});
