import { StyleSheet } from 'react-native';
import { theme } from './theme';

export default StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'space-between',
        backgroundColor: theme.colors.white,
        paddingHorizontal: 20,
    },
    nextButton: {
        marginTop: 40,
        width: '100%',
        borderRadius: theme.borderRadius.size30,
        height: 42,
        marginBottom: 40,
    },
    nextText: {
        fontSize: theme.fontSize.size16,
        fontWeight: '700',
    },
    title: {
        fontSize: theme.fontSize.size20,
        fontWeight: '700',
        color: theme.colors.blackV0,
        marginTop: 40,
    },
    selector: {
        marginBottom: 70,
    },
    subTitle: {
        fontSize: theme.fontSize.size16,
        fontWeight: '500',
        color: theme.colors.blackV1,
        marginBottom: 8,
        marginTop: 12,
    },
    alert: {
        fontSize: theme.fontSize.size12,
        fontWeight: '500',
        color: theme.colors.red,
        marginBottom: 4,
        //alignSelf: 'center',
    },
    input: {

        borderWidth: 1,
        borderColor: theme.colors.grayV2,
        width: '100%',
        paddingHorizontal: 20,
        paddingVertical: 14,
        borderRadius: theme.borderRadius.size12,
        color: theme.colors.gray2,
        fontSize: theme.fontSize.size14,
        fontWeight: '500',
        marginBottom: 10,
    },
    verifyText: {
        width: '100%',
        textAlign: 'center',
        fontSize: theme.fontSize.size14,
        fontWeight: '500',
        color: theme.colors.grayV1,
        marginBottom: 20,
        marginTop: 20,
    },
    againText: {
        width: '100%',
        textAlign: 'center',
        fontSize: theme.fontSize.size14,
        fontWeight: '500',
        color: theme.colors.Galdae,
    },
    redText: {
        fontSize: theme.fontSize.size14,
        fontWeight: '500',
        color: theme.colors.red,
        marginBottom: 4,
    },
    codeContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 10,
        marginBottom: 20,
        marginTop: 60,
    },
    codeInput: {
        width:52,
        height: 70,
        borderWidth: 0,
        borderRadius: theme.borderRadius.size12,
        fontSize: theme.fontSize.size32,
        fontWeight: '700',
        color: theme.colors.blackV0,
        backgroundColor: theme.colors.grayV2,
        textAlign: 'center',
    },
    codeInputSuccess: {
        width:52,
        height: 70,
        borderWidth: 1,
        borderRadius: theme.borderRadius.size12,
        fontSize: theme.fontSize.size32,
        fontWeight: '700',
        color: theme.colors.blackV0,
        backgroundColor: theme.colors.blue2,
        borderColor: theme.colors.blue,
        textAlign: 'center',
    },
    codeInputError: {
        width:52,
        height: 70,
        borderWidth: 1,
        borderColor: theme.colors.red,
        borderRadius: theme.borderRadius.size12,
        fontSize: theme.fontSize.size32,
        fontWeight: '700',
        color: theme.colors.blackV0,
        backgroundColor: theme.colors.red2,
        textAlign: 'center',
    },
    againButton: {
        marginTop: 43,
        width: 72,
        borderRadius: theme.borderRadius.size30,
        borderWidth: 1,
        borderColor: theme.colors.Galdae,
        height: 36,
        backgroundColor: theme.colors.white,
        paddingVertical: 0,
        paddingHorizontal: 10,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',

    },
    againText2: {
        width: '100%',
        textAlign: 'center',
        fontSize: theme.fontSize.size14,
        fontWeight: '500',
        color: theme.colors.Galdae,
    },
    noCodeText: {
        fontSize: theme.fontSize.size16,
        fontWeight: '500',
        color: theme.colors.blackV3,
        marginTop: 114,
        alignSelf: 'center',
    },
    resendText: {
        marginTop: 10,
        fontSize: theme.fontSize.size14,
        fontWeight: '500',
        color: theme.colors.blue,
        alignSelf: 'center',
        textDecorationLine: 'underline',
    },
    successText: {
        fontSize: theme.fontSize.size12,
        fontWeight: '500',
        color: theme.colors.blackV0,
        alignSelf: 'center',
    },
});
