import {StyleSheet} from 'react-native';
import {theme} from './theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'space-between',
    backgroundColor: theme.colors.white,
    paddingHorizontal: 20,
  },
  title: {
    fontSize: theme.fontSize.size20,
    fontWeight: '700',
    color: theme.colors.blackV0,
    marginBottom: 24,
  },
  alertText: {
    fontSize: theme.fontSize.size12,
    fontWeight: '500',
    color: theme.colors.red,
    marginTop: 6,
    position: 'absolute',
    left: 0,
    bottom: 10,
  },
  alertText2: {
    fontSize: theme.fontSize.size12,
    fontWeight: '500',
    color: theme.colors.blue,
    marginTop: 6,
    position: 'absolute',
    left: 0,
    bottom: 10,
  },
  profileContainer: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  profileWrapper: {
    position: 'relative',
    width: 81,
    height: 81,
  },
  // profile: {
  //   width: 68,
  //   height: 68,
  //   position: 'absolute',
  //   left: 0,
  //   right: 0,
  //   borderRadius: 999,
  // },
  profile:{
    width:62,
    height:62,
    borderRadius:999,
    backgroundColor:theme.colors.white,
    position:'relative',
  },
  profileImg:{
    width: '100%',
    height: '100%',
    borderRadius: 999,
  },
  profileCamera:{
    position:'absolute',
    bottom:0,
    right:0,
    backgroundColor:theme.colors.white,
    padding:2,
    width: 36,
    borderRadius: 999,
    height: 36,
  },
  camera: {
    width: 36,
    height: 36,
    backgroundColor: theme.colors.white,
    borderRadius: 999,
    position: 'absolute',
    bottom: -68,
    right: 0,
  },
  subTitle: {
    fontSize: theme.fontSize.size18,
    color: theme.colors.blackV0,
    fontWeight: '700',
  },
  subTitleContainer:{
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    marginBottom: 8,
  },
  required:{
    fontSize: theme.fontSize.size12,
    color: theme.colors.red,
    fontWeight: '500',
  },
  inputWrapper: {
    position: 'relative',
    marginBottom: 30,
    height: 46,
    width: '100%',
    justifyContent: 'center',
  },
  input: {
    width: '100%',
    height: 42,
    paddingLeft: 20,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    paddingRight: 70,
    borderColor: theme.colors.grayV2,
    position: 'absolute',
    fontSize: theme.fontSize.size14,
    color: theme.colors.gray2,
    fontWeight: '500',
  },
  checkBtn: {
    position: 'absolute',
    right: 10,
    top: '50%', // 세로 중앙 정렬
    transform: [{translateY: -14}],
    backgroundColor: theme.colors.grayV3,
    borderRadius: 8,
    zIndex: 999,
    width: 80,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkBtnText: {
    fontSize: theme.fontSize.size14,
    fontWeight: '500',
    color: theme.colors.gray2,
  },
  genderBtnContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 30,
  },
  genderBtn: {
    marginRight: 8,
    paddingVertical: 6,
    borderWidth: 1,

  },
  genderBtnText:{
    fontWeight: '500',
  },
  bankContainer: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.colors.grayV2,
    width: '100%',
    paddingLeft: 20,
    paddingVertical: 14,
    marginBottom: 8,
  },
  bankSelector: {
    height: 42,
    marginBottom: 12,
  },
  bankText: {
    color: theme.colors.grayV2,
    fontSize: theme.fontSize.size14,
    fontWeight: '500',
  },
  nextButton: {
    marginTop: 40,
    width: '100%',
    borderRadius: theme.borderRadius.size10,
    height: 42,
    marginBottom: 40,
  },
  nextText: {
    fontSize: theme.fontSize.size16,
    fontWeight: '700',
  },
});
