export {default as GaldaeLogo} from './GaldaeLogo.svg';
export {default as Notification} from './notification_line 1.svg';
export {default as ChatIcon} from './ChatIcon.svg';
export {default as HomeIcon} from './HomeIcon.svg';
export {default as MyInfoIcon} from './MyInfoIcon.svg';
export {default as ClickedChatIcon} from './ClickedChatIcon.svg';
export {default as ClickedHomeIcon} from './ClickedHomeIcon.svg';
export {default as ClickedMyInfoIcon} from './ClickedMyInfoIcon.svg';
export {default as More} from './More.svg';
export {default as Search} from './Search.svg';
export {default as Filter} from './Filter.svg';
export {default as GrayBag} from './GrayBag.svg';
export {default as WhiteBag} from './WhiteBag.svg';
export {default as GreenCarrier} from './GreenCarrier.svg';
export {default as Switch} from './Switch.svg';
export {default as Car} from './Car.svg';
export {default as Location} from './Location.svg';
export {default as Clock} from './Clock.svg';
export {default as User} from './User.svg';
export {default as DisabledUser} from './DisabledUser.svg';
export {default as FromToLine} from './FromToLine.svg';
export {default as Add} from './Add.svg';
export {default as Cancel} from './close_line 1.svg';
export {default as Position} from './Position.svg';
export {default as Carrier} from './Carrier.svg';
export {default as Bag} from './Bag.svg';
export {default as Check} from './Check.svg';
export {default as CheckSelected} from './CheckSelected.svg';
export {default as CheckLine} from './CheckLine.svg';
export {default as LeftArrow} from './LeftArrow.svg';
export {default as Minus} from './minimize_line 1.svg';
export {default as Plus} from './add_line 3.svg';
export {default as ToBigPic} from './fullscreen_line.svg';
export {default as ClosePic} from './fullscreen_exit_line.svg';
export {default as LocationBlack} from './LocationBlack.svg';
export {default as RightArrow} from './RightArrow.svg';
export {default as UserFill} from './UserFill.svg';
export {default as UserFillLight} from './UserFillLight.svg';
export {default as DefaultProfile} from './DefaultProfile.svg';
export {default as Send} from './Send.svg';
export {default as AddFill} from './AddFill.svg';
export {default as Picture} from './Picture.svg';
export {default as Camera} from './Camera.svg';
export {default as Money} from './Money.svg';
export {default as CloseFill} from './CloseFill.svg';
export {default as Kebab} from './Kebab.svg';
export {default as Exit} from './Exit.svg';
export {default as Bank} from './Bank.svg';
export {default as GalleryBlack} from './GalleryBlack.svg';
export {default as CancelBlack} from './CancelBlack.svg';
export {default as DownArrow} from './DownArrow.svg';
export {default as UpArrow} from './UpArrow.svg';
export {default as PictureGray} from './PictureGray.svg';
export {default as Alert} from './Alert.svg';
export {default as down_line} from './down_line 6.svg';
export {default as Separate} from './Separate.svg';
export {default as up_line} from './up_line 1.svg';
export {default as up_line_black} from './up_line_black.svg';
export {default as location_line} from './location_line 5.svg';
export {default as location_line_gray2} from './location_line_gray2.svg';
export {default as arrow_right_line} from './arrow_right_line 2.svg';
export {default as arrow_right_line_gray2} from './arrow_right_line_gray2.svg';
export {default as arrow_down_fill} from './arrow_down_fill 1.svg';
export {default as arrow_down_fill_gray2} from './arrow_down_fill_gray2.svg';
export {default as arrow_left_line} from './arrow_left_line 1.svg';
export {default as Profile} from './Profile.svg';
export {default as Badge} from './Badge.svg';
export {default as information_line} from './information_line 2.svg';
export {default as transfer_2_line} from './transfer_2_line 1.svg';
export {default as check_circle_line} from './check_circle_line 1.svg';
export {default as check_circle_fill} from './check_circle_fill 1.svg';
export {default as CorrectEx} from './CorrectEx.svg';
export {default as WrongEx} from './WrongEx.svg';
export {default as Progress} from './Progress.svg';
export {default as camera_2_line} from './camera_2_line 1.svg';
export {default as edit_line} from './edit_line 1.svg';
export {default as right_line} from './right_line 1.svg';
export {default as information} from './information_line 3.svg';
export {default as down} from './down_line 5.svg';
export {default as service_line} from './service_line 1.svg';
export {default as pic_line} from './pic_line 2.svg';
export {default as add_line} from './add_line 2.svg';
export {default as Bank_Busan} from './Bank_Busan.svg';
export {default as Bank_Citi} from './Bank_Citi.svg';
export {default as Bank_DaeGu} from './Bank_DaeGu.svg';
export {default as Bank_ForestryCooperative} from './Bank_ForestryCooperative.svg';
export {default as Bank_Hana} from './Bank_Hana.svg';
export {default as Bank_IBK} from './Bank_IBK.svg';
export {default as Bank_Jeju} from './Bank_Jeju.svg';
export {default as Bank_Jeonbuk} from './Bank_Jeonbuk.svg';
export {default as Bank_K} from './Bank_K.svg';
export {default as Bank_Kakao} from './Bank_Kakao.svg';
export {default as Bank_KB} from './Bank_KB.svg';
export {default as Bank_KEB} from './Bank_KEB.svg';
export {default as Bank_KoreaInvestment} from './Bank_KoreaInvestment.svg';
export {default as Bank_KWANGJU} from './Bank_KWANGJU.svg';
export {default as Bank_NACUFOK} from './Bank_NACUFOK.svg';
export {default as Bank_NHINVESTMENT} from './Bank_NHINVESTMENT.svg';
export {default as Bank_Postbank} from './Bank_Postbank.svg';
export {default as Bank_SavingsBank} from './Bank_SavingsBank.svg';
export {default as Bank_SBI} from './Bank_SBI.svg';
export {default as Bank_SC} from './Bank_SC.svg';
export {default as Bank_Suhyup} from './Bank_Suhyup.svg';
export {default as Bank_Toss} from './Bank_Toss.svg';
export {default as Bank_Woori} from './Bank_Woori.svg';
export {default as Bank_KDB} from './Bank_KDB.svg';
export {default as Bank_Saemaul} from './Bank_Saemaul.svg';
