export {default as GaldaeLogo} from './GaldaeLogo.svg';
export {default as Notification} from './notification_line 1.svg';
export {default as ChatIcon} from './ChatIcon.svg';
export {default as HomeIcon} from './HomeIcon.svg';
export {default as MyInfoIcon} from './MyInfoIcon.svg';
export {default as ClickedChatIcon} from './ClickedChatIcon.svg';
export {default as ClickedHomeIcon} from './ClickedHomeIcon.svg';
export {default as ClickedMyInfoIcon} from './ClickedMyInfoIcon.svg';
export {default as More} from './More.svg';
export {default as Search} from './Search.svg';
export {default as Filter} from './Filter.svg';
export {default as GrayBag} from './GrayBag.svg';
export {default as WhiteBag} from './WhiteBag.svg';
export {default as GreenCarrier} from './GreenCarrier.svg';
export {default as Switch} from './Switch.svg';
export {default as Car} from './Car.svg';
export {default as Location} from './Location.svg';
export {default as Clock} from './Clock.svg';
export {default as User} from './User.svg';
export {default as DisabledUser} from './DisabledUser.svg';
export {default as FromToLine} from './FromToLine.svg';
export {default as Add} from './Add.svg';
export {default as Cancel} from './close_line 1.svg';
export {default as Position} from './Position.svg';
export {default as Carrier} from './Carrier.svg';
export {default as Bag} from './Bag.svg';
export {default as Check} from './Check.svg';
export {default as CheckSelected} from './CheckSelected.svg';
export {default as LeftArrow} from './LeftArrow.svg';
export {default as Minus} from './minimize_line 1.svg';
export {default as Plus} from './add_line 3.svg';
export {default as ToBigPic} from './fullscreen_line.svg';
export {default as ClosePic} from './fullscreen_exit_line.svg';
export {default as down_line} from './down_line 6.svg';
export {default as Separate} from './Separate.svg';
export {default as up_line} from './up_line 1.svg';
export {default as location_line} from './location_line 5.svg';
export {default as arrow_right_line} from './arrow_right_line 2.svg';
export {default as arrow_down_fill} from './arrow_down_fill 1.svg';
export {default as arrow_left_line} from './arrow_left_line 1.svg';
